### ISSUE TITLE
Add Logging with logfile rotation, increase logging level to info

### ISSUE THREAD

**Issue by acedrew** [ut-cuip/utc-cuip-video-event-producer#7]
Currently the webserver logging is set to level ERROR, avoiding writing context that would help troubleshoot issues. Also, each try/except block should catch the exception and pass it to the logger before handling.

Once instrumented here, we'll pick up the logfiles and send them to a centralized logging system

**Comment by oitsjustjose** [comment]
Actually this isn’t even working because it’s done in the main process but doesn’t apply to the separate processes. So really this doesn’t cause any issues anyways. The main reason I had done this was to remove log spam from each connection to the stream.

**Comment by oitsjustjose** [comment]
But you’re right about the try catch, and I’ll remove the setting logging level

**Comment by oitsjustjose** [comment]
How do you suggest we handle logging? I've found a few implementations and can think of a few of my own, but I feel like they're all subpar.

**Comment by acedrew** [comment]
I pretty sure the logger is pickleable, so you can pass it in, or you can pass in the global parameters, and let each process instantiate its own logger with a few local parameters, like the name of the component (producer, frameprocessor, etc) (probably ideal)
With what we're doing with log handling centrally, it's best to just have logger write to file and manage rotation

**Comment by oitsjustjose** [comment]
Alright, I just [wrote a quick multiprocessing test](https://gist.github.com/oitsjustjose/fe0298778af2748bb7df12bc92a789d3#file-mp_logging_test-py) to see if logging to a file handles contention itself or if I needed to handle it myself - it does it for me so we're in the clear.

How should we format our logfile names?

**Comment by oitsjustjose** [comment]
Alright so after **two hours** of figuring out how to properly catch errors and redirect them to `logging.getLogger()` and never succeeding, I'm voting we go with a library called LogBook. It took 2 minutes to get logging outputting to the same file, including errors.

**Comment by oitsjustjose** [comment]
```python
import multiprocessing
import sys
import time
from datetime import datetime
import traceback

from logbook import Logger, FileHandler


def test(logger, name):
    start_time = time.time()
    while True:
        try:
            if time.time() - start_time > 5:
                a = 1 / 0
            logger.info("{}: {}".format(name, datetime.fromtimestamp(time.time())))
            time.sleep(1)
        except Exception as e:
            logger.error(e)
            logger.error(traceback.format_exc())
            return


def main():
    log_handler = FileHandler('application.log')
    log_handler.push_application()
    loggers = [Logger("test_{}".format(x)) for x in range(5)]
    procs = []
    for i in range(len(loggers)):
        procs.append(
            multiprocessing.Process(
                target=test, args=(loggers[i], "process_{}".format(i))
            )
        )

    try:
        for proc in procs:
            proc.start()
        for proc in procs:
            proc.join()
    except KeyboardInterrupt:
        for proc in procs:
            proc.terminate()
    except Exception as e:
        
        for proc in procs:
            proc.terminate()


if __name__ == "__main__":
    main()
```

Result:
```
[2019-03-23 21:48:13.864367] INFO: test_0: process_0: 2019-03-23 17:48:13.863670
[2019-03-23 21:48:13.865692] INFO: test_1: process_1: 2019-03-23 17:48:13.864454
[2019-03-23 21:48:13.866392] INFO: test_2: process_2: 2019-03-23 17:48:13.865034
[2019-03-23 21:48:13.867293] INFO: test_3: process_3: 2019-03-23 17:48:13.865718
[2019-03-23 21:48:13.868205] INFO: test_4: process_4: 2019-03-23 17:48:13.867640
[2019-03-23 21:48:14.866488] INFO: test_0: process_0: 2019-03-23 17:48:14.865771
[2019-03-23 21:48:14.867188] INFO: test_1: process_1: 2019-03-23 17:48:14.866576
[2019-03-23 21:48:14.867983] INFO: test_2: process_2: 2019-03-23 17:48:14.867444
[2019-03-23 21:48:14.868769] INFO: test_3: process_3: 2019-03-23 17:48:14.868010
[2019-03-23 21:48:14.869348] INFO: test_4: process_4: 2019-03-23 17:48:14.868776
[2019-03-23 21:48:15.868674] INFO: test_1: process_1: 2019-03-23 17:48:15.867986
[2019-03-23 21:48:15.868748] INFO: test_0: process_0: 2019-03-23 17:48:15.867944
[2019-03-23 21:48:15.869425] INFO: test_2: process_2: 2019-03-23 17:48:15.868997
[2019-03-23 21:48:15.869621] INFO: test_3: process_3: 2019-03-23 17:48:15.869239
[2019-03-23 21:48:15.870473] INFO: test_4: process_4: 2019-03-23 17:48:15.870040
[2019-03-23 21:48:16.870953] INFO: test_0: process_0: 2019-03-23 17:48:16.870231
[2019-03-23 21:48:16.870962] INFO: test_3: process_3: 2019-03-23 17:48:16.870248
[2019-03-23 21:48:16.871023] INFO: test_1: process_1: 2019-03-23 17:48:16.870195
[2019-03-23 21:48:16.871066] INFO: test_2: process_2: 2019-03-23 17:48:16.870247
[2019-03-23 21:48:16.871739] INFO: test_4: process_4: 2019-03-23 17:48:16.871244
[2019-03-23 21:48:17.873258] INFO: test_2: process_2: 2019-03-23 17:48:17.872533
[2019-03-23 21:48:17.873325] INFO: test_1: process_1: 2019-03-23 17:48:17.872532
[2019-03-23 21:48:17.873250] INFO: test_0: process_0: 2019-03-23 17:48:17.872472
[2019-03-23 21:48:17.873257] INFO: test_3: process_3: 2019-03-23 17:48:17.872509
[2019-03-23 21:48:17.873367] INFO: test_4: process_4: 2019-03-23 17:48:17.872534
[2019-03-23 21:48:18.874987] ERROR: test_1: division by zero
[2019-03-23 21:48:18.875002] ERROR: test_4: division by zero
[2019-03-23 21:48:18.874998] ERROR: test_3: division by zero
[2019-03-23 21:48:18.875001] ERROR: test_2: division by zero
[2019-03-23 21:48:18.874998] ERROR: test_0: division by zero
[2019-03-23 21:48:18.876749] ERROR: test_1: Traceback (most recent call last):
  File "Test.py", line 15, in test
    a = 1 / 0
ZeroDivisionError: division by zero

[2019-03-23 21:48:18.876769] ERROR: test_4: Traceback (most recent call last):
  File "Test.py", line 15, in test
    a = 1 / 0
ZeroDivisionError: division by zero

[2019-03-23 21:48:18.876802] ERROR: test_3: Traceback (most recent call last):
  File "Test.py", line 15, in test
    a = 1 / 0
ZeroDivisionError: division by zero

[2019-03-23 21:48:18.876826] ERROR: test_0: Traceback (most recent call last):
  File "Test.py", line 15, in test
    a = 1 / 0
ZeroDivisionError: division by zero

[2019-03-23 21:48:18.876870] ERROR: test_2: Traceback (most recent call last):
  File "Test.py", line 15, in test
    a = 1 / 0
ZeroDivisionError: division by zero
```
LogBook made this incredibly easy.

**Comment by oitsjustjose** [comment]
And one last thing: LogBook also handles [log rotation(https://logbook.readthedocs.io/en/stable/api/handlers.html)

**Comment by acedrew** [comment]
/var/log/video-events-producer/stream-processor-camera-id.log
""/kafka-producer.log
""/frame-processor.log
Or something similar if it makes more sense to you? I'm not sure about having the camera-id in in log name, but I'm also not sure about how to split up the stream processors...

**Comment by oitsjustjose** [comment]
You think we should split up the stream processors or just put all into one and pre-pend the camera id to any logs?

**Comment by acedrew** [comment]
I think the stream processors should have their own logger instances, and log to separate files, just to minimize any potential contention issues.

**Comment by oitsjustjose** [comment]
Make sense. Is the LogBook library ok or should we use something else like Log4J?

**Comment by acedrew** [comment]
LogBook is fine, log4j is just the Java equivalent of logger in python, because there's not a decent logging system in the Java standard lib. I'm not sure why logger wasn't working for you, but whatever works without negatively impacting performance.

**Comment by oitsjustjose** [comment]
See I thought Log4J was java only, but Austin had brought it up for this project so I had assumed he knew if it was available for Python too or not..

**Comment by oitsjustjose** [comment]
This has been completed for a while, my bad.
